// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvEtOIklrAqLOupJPWaWn0UwaX6SKiuSk',
    appId: '1:833618051245:web:47b6157ae0cdfa21764624',
    messagingSenderId: '833618051245',
    projectId: 'futter-firebase-t-i-0414',
    authDomain: 'futter-firebase-t-i-0414.firebaseapp.com',
    storageBucket: 'futter-firebase-t-i-0414.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfX01Rs5tNpGSXe1B3d992dY65_VvbgPE',
    appId: '1:833618051245:android:3730a038144b8411764624',
    messagingSenderId: '833618051245',
    projectId: 'futter-firebase-t-i-0414',
    storageBucket: 'futter-firebase-t-i-0414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0KguHdf5UmqH8ioJKlt4WruGNpr_QnT8',
    appId: '1:833618051245:ios:d0055b830150d647764624',
    messagingSenderId: '833618051245',
    projectId: 'futter-firebase-t-i-0414',
    storageBucket: 'futter-firebase-t-i-0414.appspot.com',
    iosClientId: '833618051245-4olmkoqjhm3gfv15tns05fs4uksj54ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSampleApp',
  );
}
